import { SlideTableColors, SlideTheme } from '../types/slide-theme.types';

const tableColors: SlideTableColors = {
  backgroundColor: '#FFFFFF',
  headerBackgroundColor: '#fff9e7',
  headerTextColor: '#8d6e0d',
  textColor: '#000000',
  cellBackgroundColor: '#FFFFFF',
};

export type ColorPalette = {
  id: string;
  name: string;
  colors: {
    title: string;
    text: string;
    shape: string;
    rectangle: string;
    circle: string;
    line: string;
    background: string;
  };
  backgroundColor?: string;
};

export const colorPalettes: ColorPalette[] = [
  {
    id: 'white',
    name: 'White',
    colors: {
      title: '#5880F1',
      text: '#0F1519',
      shape: '#FFE080',
      rectangle: '#FFE080',
      circle: '#FFE080',
      line: '#FFE080',
      background: '#FFFFFF',
    },
    backgroundColor: '#D2DEFF',
  },
  {
    id: 'dark-mode',
    name: 'Dark mode',
    colors: {
      title: '#FFFFFF',
      text: '#FFFFFF',
      shape: '#323E47',
      rectangle: '#323E47',
      circle: '#323E47',
      line: '#323E47',
      background: '#11151A',
    },
    backgroundColor: '#323E47',
  },
  {
    id: 'light-blue',
    name: 'light blue',
    colors: {
      title: '#161C2E',
      text: '#161C2E',
      shape: '#176AFF',
      rectangle: '#176AFF',
      circle: '#176AFF',
      line: '#176AFF',
      background: '#CAE6FF',
    },
    backgroundColor: '#FFFFFF',
  },
  {
    id: 'light-yellow',
    name: 'light yellow',
    colors: {
      title: '#0D0E12',
      text: '#0D0E12',
      shape: '#FFF4D0',
      rectangle: '#FFF4D0',
      circle: '#FFF4D0',
      line: '#FFF4D0',
      background: '#FFFEF4',
    },
    backgroundColor: '#FFEAAB',
  },
  {
    id: 'dark-blackboard',
    name: 'dark (blackboard)',
    colors: {
      title: '#FFFFFF',
      text: '#FFFFFF',
      shape: '#6180ED',
      rectangle: '#6180ED',
      circle: '#6180ED',
      line: '#6180ED',
      background: '#242424',
    },
    backgroundColor: '#CAE6FF',
  },
  {
    id: 'light-gradient',
    name: 'light gradient',
    colors: {
      title: '#161C2E',
      text: '#161C2E',
      shape: '#D2DEFF',
      rectangle: '#D2DEFF',
      circle: '#D2DEFF',
      line: '#D2DEFF',
      background: '#EDF2FF',
    },
    backgroundColor: '#FFFFFF',
  },
  {
    id: 'green',
    name: 'Green',
    colors: {
      title: '#1E1E1E',
      text: '#1E1E1E',
      shape: '#086375',
      rectangle: '#086375',
      circle: '#086375',
      line: '#086375',
      background: '#77C7C1',
    },
    backgroundColor: '#9DDAD6',
  },
];

export const deepKnowledge: SlideTheme = {
  name: 'Deep Knowledge',
  cover: {
    backgroundColor: '#5880f1',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#FFE080',
    accentColor: '#ffd91e',
    rectangleColor: '#3055BF',
    circleColor: '#B8D4FF',
    lineColor: '#FFE080',
  },
  summary: {
    backgroundColor: '#5880f1',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#FFE080',
    accentColor: '#ffd91e',
    rectangleColor: '#3055BF',
    circleColor: '#B8D4FF',
    lineColor: '#FFE080',
  },
  developmentBullet: {
    backgroundColor: '#5880f1',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#FFE080',
    accentColor: '#ffd91e',
    rectangleColor: '#3055BF',
    circleColor: '#B8D4FF',
    lineColor: '#FFE080',
  },
  developmentText: {
    backgroundColor: '#5880f1',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#FFE080',
    accentColor: '#ffd91e',
    rectangleColor: '#3055BF',
    circleColor: '#B8D4FF',
    lineColor: '#FFE080',
  },
  twoColumns: {
    backgroundColor: '#5880f1',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#FFE080',
    accentColor: '#ffd91e',
    rectangleColor: '#3055BF',
    circleColor: '#B8D4FF',
    lineColor: '#FFE080',
  },
  exercise: {
    backgroundColor: '#FFFFFF',
    titleColor: '#000000',
    subtitleColor: '#262626',
    paragraphColor: '#262626',
    shapeColor: '#FFE080',
    accentColor: '#ffd91e',
    rectangleColor: '#3055BF',
    circleColor: '#B8D4FF',
    lineColor: '#FFE080',
  },
  mainImage: {
    backgroundColor: '#5880f1',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#FFE080',
    accentColor: '#ffd91e',
    rectangleColor: '#3055BF',
    circleColor: '#B8D4FF',
    lineColor: '#FFE080',
  },
  bigImage: {
    backgroundColor: '#5880f1',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#FFE080',
    accentColor: '#ffd91e',
    rectangleColor: '#3055BF',
    circleColor: '#B8D4FF',
    lineColor: '#FFE080',
  },
  conclusion: {
    backgroundColor: '#5880f1',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#FFE080',
    accentColor: '#ffd91e',
    rectangleColor: '#3055BF',
    circleColor: '#B8D4FF',
    lineColor: '#FFE080',
  },
  table: tableColors,
  cards: {
    backgroundColor: '#5880f1',
    titleColor: '#FFFFFF',
    subtitleColor: '#0F151A',
    paragraphColor: '#FFFFFF',
    shapeColor: '#FFE080',
    accentColor: '#ffd91e',
    rectangleColor: '#3055BF',
    circleColor: '#B8D4FF',
    lineColor: '#FFE080',
  },
};

export const lightFun: SlideTheme = {
  name: 'Light Fun',
  cover: {
    backgroundColor: '#FFFFFF',
    titleColor: '#5880F1',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#FFE080',
    accentColor: '#5880F1',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#FFE080',
  },
  summary: {
    backgroundColor: '#FFFFFF',
    titleColor: '#5880F1',
    subtitleColor: '#5880F1',
    paragraphColor: '#323E47',
    shapeColor: '#FFE080',
    accentColor: '#5880F1',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#FFE080',
  },
  developmentBullet: {
    backgroundColor: '#FFFFFF',
    titleColor: '#5880F1',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#FFE080',
    accentColor: '#5880F1',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#FFE080',
  },
  developmentText: {
    backgroundColor: '#FFFFFF',
    titleColor: '#5880F1',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#FFE080',
    accentColor: '#5880F1',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#FFE080',
  },
  twoColumns: {
    backgroundColor: '#FFFFFF',
    titleColor: '#5880F1',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#FFE080',
    accentColor: '#5880F1',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#FFE080',
  },
  exercise: {
    backgroundColor: '#FFFFFF',
    titleColor: '#5880F1',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#FFE080',
    accentColor: '#5880F1',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#FFE080',
  },
  mainImage: {
    backgroundColor: '#FFFFFF',
    titleColor: '#5880F1',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#FFE080',
    accentColor: '#5880F1',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#FFE080',
  },
  bigImage: {
    backgroundColor: '#FFFFFF',
    titleColor: '#5880F1',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#FFE080',
    accentColor: '#5880F1',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#FFE080',
  },
  conclusion: {
    backgroundColor: '#FFFFFF',
    titleColor: '#5880F1',
    subtitleColor: '#5880F1',
    paragraphColor: '#323E47',
    shapeColor: '#FFE080',
    accentColor: '#5880F1',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#FFE080',
  },
  table: {
    backgroundColor: '#FFFFFF',
    headerBackgroundColor: '#EDF2FF',
    headerTextColor: '#3055bf',
    textColor: '#0F151A',
    cellBackgroundColor: '#FFFFFF',
  },
  cards: {
    backgroundColor: '#FFFFFF',
    titleColor: '#5880F1',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#FFE080',
    accentColor: '#5880F1',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#FFE080',
  },
};

export const softSky: SlideTheme = {
  name: 'Soft Sky',
  cover: {
    backgroundColor: '#D2DEFF',
    titleColor: '#1A2375',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#5880F1',
    accentColor: '#5880F1',
    rectangleColor: '#99B4FF',
    circleColor: '#9BB8FF',
    lineColor: '#5880F1',
  },
  summary: {
    backgroundColor: '#D2DEFF',
    titleColor: '#1A2375',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#5880F1',
    accentColor: '#5880F1',
    rectangleColor: '#99B4FF',
    circleColor: '#9BB8FF',
    lineColor: '#5880F1',
  },
  developmentBullet: {
    backgroundColor: '#D2DEFF',
    titleColor: '#1A2375',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#5880F1',
    accentColor: '#5880F1',
    rectangleColor: '#99B4FF',
    circleColor: '#9BB8FF',
    lineColor: '#5880F1',
  },
  developmentText: {
    backgroundColor: '#D2DEFF',
    titleColor: '#1A2375',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#5880F1',
    accentColor: '#5880F1',
    rectangleColor: '#99B4FF',
    circleColor: '#9BB8FF',
    lineColor: '#5880F1',
  },
  twoColumns: {
    backgroundColor: '#D2DEFF',
    titleColor: '#1A2375',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#5880F1',
    accentColor: '#5880F1',
    rectangleColor: '#99B4FF',
    circleColor: '#9BB8FF',
    lineColor: '#5880F1',
  },
  exercise: {
    backgroundColor: '#D2DEFF',
    titleColor: '#1A2375',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#5880F1',
    accentColor: '#5880F1',
    rectangleColor: '#99B4FF',
    circleColor: '#9BB8FF',
    lineColor: '#5880F1',
  },
  mainImage: {
    backgroundColor: '#D2DEFF',
    titleColor: '#1A2375',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#5880F1',
    accentColor: '#5880F1',
    rectangleColor: '#99B4FF',
    circleColor: '#9BB8FF',
    lineColor: '#5880F1',
  },
  bigImage: {
    backgroundColor: '#D2DEFF',
    titleColor: '#1A2375',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#5880F1',
    accentColor: '#5880F1',
    rectangleColor: '#3055BF',
    circleColor: '#9BB8FF',
    lineColor: '#5880F1',
  },
  conclusion: {
    backgroundColor: '#D2DEFF',
    titleColor: '#1A2375',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#5880F1',
    accentColor: '#5880F1',
    rectangleColor: '#99B4FF',
    circleColor: '#9BB8FF',
    lineColor: '#5880F1',
  },
  table: {
    backgroundColor: '#D2DEFF',
    headerBackgroundColor: '#EDF2FF',
    headerTextColor: '#1A2375',
    textColor: '#0F151A',
    cellBackgroundColor: '#FFFFFF',
  },
  cards: {
    backgroundColor: '#D2DEFF',
    titleColor: '#1A2375',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#5880F1',
    accentColor: '#5880F1',
    rectangleColor: '#99B4FF',
    circleColor: '#9BB8FF',
    lineColor: '#5880F1',
  },
};

export const growingIdeas: SlideTheme = {
  name: 'Growing Ideas',
  cover: {
    backgroundColor: '#008F87',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#FFE080',
    accentColor: '#FFE080',
    rectangleColor: '#03746E',
    circleColor: '#6BC5C0',
    lineColor: '#FFE080',
  },
  summary: {
    backgroundColor: '#008F87',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#FFE080',
    accentColor: '#FFE080',
    rectangleColor: '#03746E',
    circleColor: '#6BC5C0',
    lineColor: '#FFE080',
  },
  developmentBullet: {
    backgroundColor: '#008F87',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#FFE080',
    accentColor: '#FFE080',
    rectangleColor: '#03746E',
    circleColor: '#6BC5C0',
    lineColor: '#FFE080',
  },
  developmentText: {
    backgroundColor: '#008F87',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#FFE080',
    accentColor: '#FFE080',
    rectangleColor: '#03746E',
    circleColor: '#6BC5C0',
    lineColor: '#FFE080',
  },
  twoColumns: {
    backgroundColor: '#008F87',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#FFE080',
    accentColor: '#FFE080',
    rectangleColor: '#03746E',
    circleColor: '#6BC5C0',
    lineColor: '#FFE080',
  },
  exercise: {
    backgroundColor: '#008F87',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#FFE080',
    accentColor: '#FFE080',
    rectangleColor: '#03746E',
    circleColor: '#6BC5C0',
    lineColor: '#FFE080',
  },
  mainImage: {
    backgroundColor: '#008F87',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#FFE080',
    accentColor: '#FFE080',
    rectangleColor: '#03746E',
    circleColor: '#6BC5C0',
    lineColor: '#FFE080',
  },
  bigImage: {
    backgroundColor: '#008F87',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#FFE080',
    accentColor: '#FFE080',
    rectangleColor: '#03746E',
    circleColor: '#6BC5C0',
    lineColor: '#FFE080',
  },
  conclusion: {
    backgroundColor: '#008F87',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#FFE080',
    accentColor: '#FFE080',
    rectangleColor: '#03746E',
    circleColor: '#6BC5C0',
    lineColor: '#FFE080',
  },
  table: {
    backgroundColor: '#008F87',
    headerBackgroundColor: '#FFF9E7',
    headerTextColor: '#8D6E0D',
    textColor: '#0F151A',
    cellBackgroundColor: '#FFFFFF',
  },
  cards: {
    backgroundColor: '#008F87',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#FFE080',
    accentColor: '#FFE080',
    rectangleColor: '#03746E',
    circleColor: '#6BC5C0',
    lineColor: '#FFE080',
  },
};

export const gentleNature: SlideTheme = {
  name: 'Gentle Nature',
  cover: {
    backgroundColor: '#C6E9E7',
    titleColor: '#1A2375',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#008F87',
    accentColor: '#008F87',
    rectangleColor: '#A3D9D5',
    circleColor: '#A0E0DC',
    lineColor: '#008F87',
  },
  summary: {
    backgroundColor: '#C6E9E7',
    titleColor: '#1A2375',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#008F87',
    accentColor: '#008F87',
    rectangleColor: '#A3D9D5',
    circleColor: '#A0E0DC',
    lineColor: '#008F87',
  },
  developmentBullet: {
    backgroundColor: '#C6E9E7',
    titleColor: '#1A2375',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#008F87',
    accentColor: '#008F87',
    rectangleColor: '#A3D9D5',
    circleColor: '#A0E0DC',
    lineColor: '#008F87',
  },
  developmentText: {
    backgroundColor: '#C6E9E7',
    titleColor: '#1A2375',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#008F87',
    accentColor: '#008F87',
    rectangleColor: '#A3D9D5',
    circleColor: '#A0E0DC',
    lineColor: '#008F87',
  },
  twoColumns: {
    backgroundColor: '#C6E9E7',
    titleColor: '#1A2375',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#008F87',
    accentColor: '#008F87',
    rectangleColor: '#A3D9D5',
    circleColor: '#A0E0DC',
    lineColor: '#008F87',
  },
  exercise: {
    backgroundColor: '#C6E9E7',
    titleColor: '#1A2375',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#008F87',
    accentColor: '#008F87',
    rectangleColor: '#A3D9D5',
    circleColor: '#A0E0DC',
    lineColor: '#008F87',
  },
  mainImage: {
    backgroundColor: '#C6E9E7',
    titleColor: '#1A2375',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#008F87',
    accentColor: '#008F87',
    rectangleColor: '#A3D9D5',
    circleColor: '#A0E0DC',
    lineColor: '#008F87',
  },
  bigImage: {
    backgroundColor: '#C6E9E7',
    titleColor: '#1A2375',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#008F87',
    accentColor: '#008F87',
    rectangleColor: '#A3D9D5',
    circleColor: '#A0E0DC',
    lineColor: '#008F87',
  },
  conclusion: {
    backgroundColor: '#C6E9E7',
    titleColor: '#1A2375',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#008F87',
    accentColor: '#008F87',
    rectangleColor: '#A3D9D5',
    circleColor: '#A0E0DC',
    lineColor: '#008F87',
  },
  table: {
    backgroundColor: '#C6E9E7',
    headerBackgroundColor: '#E2FAF8',
    headerTextColor: '#1A2375',
    textColor: '#0F151A',
    cellBackgroundColor: '#FFFFFF',
  },
  cards: {
    backgroundColor: '#C6E9E7',
    titleColor: '#1A2375',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#008F87',
    accentColor: '#008F87',
    rectangleColor: '#A3D9D5',
    circleColor: '#A0E0DC',
    lineColor: '#008F87',
  },
};

export const brightMinds: SlideTheme = {
  name: 'Bright Minds',
  cover: {
    backgroundColor: '#C7A232',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#FFE080',
    accentColor: '#FFE080',
    rectangleColor: '#A3821B',
    circleColor: '#F0D470',
    lineColor: '#FFE080',
  },
  summary: {
    backgroundColor: '#C7A232',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#FFE080',
    accentColor: '#FFE080',
    rectangleColor: '#A3821B',
    circleColor: '#F0D470',
    lineColor: '#FFE080',
  },
  developmentBullet: {
    backgroundColor: '#C7A232',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#FFE080',
    accentColor: '#FFE080',
    rectangleColor: '#A3821B',
    circleColor: '#F0D470',
    lineColor: '#FFE080',
  },
  developmentText: {
    backgroundColor: '#C7A232',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#FFE080',
    accentColor: '#FFE080',
    rectangleColor: '#A3821B',
    circleColor: '#F0D470',
    lineColor: '#FFE080',
  },
  twoColumns: {
    backgroundColor: '#C7A232',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#FFE080',
    accentColor: '#FFE080',
    rectangleColor: '#A3821B',
    circleColor: '#F0D470',
    lineColor: '#FFE080',
  },
  exercise: {
    backgroundColor: '#C7A232',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#FFE080',
    accentColor: '#FFE080',
    rectangleColor: '#A3821B',
    circleColor: '#F0D470',
    lineColor: '#FFE080',
  },
  mainImage: {
    backgroundColor: '#C7A232',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#FFE080',
    accentColor: '#FFE080',
    rectangleColor: '#A3821B',
    circleColor: '#F0D470',
    lineColor: '#FFE080',
  },
  bigImage: {
    backgroundColor: '#C7A232',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#FFE080',
    accentColor: '#FFE080',
    rectangleColor: '#A3821B',
    circleColor: '#F0D470',
    lineColor: '#FFE080',
  },
  conclusion: {
    backgroundColor: '#C7A232',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#FFE080',
    accentColor: '#FFE080',
    rectangleColor: '#A3821B',
    circleColor: '#F0D470',
    lineColor: '#FFE080',
  },
  table: {
    backgroundColor: '#C7A232',
    headerBackgroundColor: '#FFF9E7',
    headerTextColor: '#8D6E0D',
    textColor: '#0F151A',
    cellBackgroundColor: '#FFFFFF',
  },
  cards: {
    backgroundColor: '#C7A232',
    titleColor: '#FFFFFF',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#FFE080',
    accentColor: '#FFE080',
    rectangleColor: '#A3821B',
    circleColor: '#F0D470',
    lineColor: '#FFE080',
  },
};

export const sunnyClassroom: SlideTheme = {
  name: 'Sunny Classroom',
  cover: {
    backgroundColor: '#FFEAAB',
    titleColor: '#0F151A',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#C7A232',
    accentColor: '#C7A232',
    rectangleColor: '#FFDB6E',
    circleColor: '#FFE0A0',
    lineColor: '#C7A232',
  },
  summary: {
    backgroundColor: '#FFEAAB',
    titleColor: '#0F151A',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#C7A232',
    accentColor: '#C7A232',
    rectangleColor: '#FFDB6E',
    circleColor: '#FFE0A0',
    lineColor: '#C7A232',
  },
  developmentBullet: {
    backgroundColor: '#FFEAAB',
    titleColor: '#0F151A',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#C7A232',
    accentColor: '#C7A232',
    rectangleColor: '#FFDB6E',
    circleColor: '#FFE0A0',
    lineColor: '#C7A232',
  },
  developmentText: {
    backgroundColor: '#FFEAAB',
    titleColor: '#0F151A',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#C7A232',
    accentColor: '#C7A232',
    rectangleColor: '#FFDB6E',
    circleColor: '#FFE0A0',
    lineColor: '#C7A232',
  },
  twoColumns: {
    backgroundColor: '#FFEAAB',
    titleColor: '#0F151A',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#C7A232',
    accentColor: '#C7A232',
    rectangleColor: '#FFDB6E',
    circleColor: '#FFE0A0',
    lineColor: '#C7A232',
  },
  exercise: {
    backgroundColor: '#FFEAAB',
    titleColor: '#0F151A',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#C7A232',
    accentColor: '#C7A232',
    rectangleColor: '#FFDB6E',
    circleColor: '#FFE0A0',
    lineColor: '#C7A232',
  },
  mainImage: {
    backgroundColor: '#FFEAAB',
    titleColor: '#0F151A',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#C7A232',
    accentColor: '#C7A232',
    rectangleColor: '#FFDB6E',
    circleColor: '#FFE0A0',
    lineColor: '#C7A232',
  },
  bigImage: {
    backgroundColor: '#FFEAAB',
    titleColor: '#0F151A',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#C7A232',
    accentColor: '#C7A232',
    rectangleColor: '#FFDB6E',
    circleColor: '#FFE0A0',
    lineColor: '#C7A232',
  },
  conclusion: {
    backgroundColor: '#FFEAAB',
    titleColor: '#0F151A',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#C7A232',
    accentColor: '#C7A232',
    rectangleColor: '#FFDB6E',
    circleColor: '#FFE0A0',
    lineColor: '#C7A232',
  },
  table: {
    backgroundColor: '#FFEAAB',
    headerBackgroundColor: '#FFF9E7',
    headerTextColor: '#0F151A',
    textColor: '#0F151A',
    cellBackgroundColor: '#FFFFFF',
  },
  cards: {
    backgroundColor: '#FFEAAB',
    titleColor: '#0F151A',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#C7A232',
    accentColor: '#C7A232',
    rectangleColor: '#FFDB6E',
    circleColor: '#FFE0A0',
    lineColor: '#C7A232',
  },
};

export const classicChalk: SlideTheme = {
  name: 'Classic Chalk',
  cover: {
    backgroundColor: '#FFFFFF',
    titleColor: '#0F151A',
    subtitleColor: '#0F151A',
    paragraphColor: '#323E47',
    shapeColor: '#D5E1ED',
    accentColor: '#D5E1ED',
    rectangleColor: '#D5E1ED',
    circleColor: '#D5E1ED',
    lineColor: '#92A6B2',
  },
  summary: {
    backgroundColor: '#FFFFFF',
    titleColor: '#0F151A',
    subtitleColor: '#0F151A',
    paragraphColor: '#323E47',
    shapeColor: '#D5E1ED',
    accentColor: '#D5E1ED',
    rectangleColor: '#D5E1ED',
    circleColor: '#D5E1ED',
    lineColor: '#92A6B2',
  },
  developmentBullet: {
    backgroundColor: '#FFFFFF',
    titleColor: '#0F151A',
    subtitleColor: '#0F151A',
    paragraphColor: '#323E47',
    shapeColor: '#D5E1ED',
    accentColor: '#D5E1ED',
    rectangleColor: '#D5E1ED',
    circleColor: '#D5E1ED',
    lineColor: '#92A6B2',
  },
  developmentText: {
    backgroundColor: '#FFFFFF',
    titleColor: '#0F151A',
    subtitleColor: '#0F151A',
    paragraphColor: '#323E47',
    shapeColor: '#D5E1ED',
    accentColor: '#D5E1ED',
    rectangleColor: '#D5E1ED',
    circleColor: '#D5E1ED',
    lineColor: '#92A6B2',
  },
  twoColumns: {
    backgroundColor: '#FFFFFF',
    titleColor: '#0F151A',
    subtitleColor: '#0F151A',
    paragraphColor: '#323E47',
    shapeColor: '#D5E1ED',
    accentColor: '#D5E1ED',
    rectangleColor: '#D5E1ED',
    circleColor: '#D5E1ED',
    lineColor: '#92A6B2',
  },
  exercise: {
    backgroundColor: '#FFFFFF',
    titleColor: '#0F151A',
    subtitleColor: '#0F151A',
    paragraphColor: '#323E47',
    shapeColor: '#D5E1ED',
    accentColor: '#D5E1ED',
    rectangleColor: '#D5E1ED',
    circleColor: '#D5E1ED',
    lineColor: '#92A6B2',
  },
  mainImage: {
    backgroundColor: '#FFFFFF',
    titleColor: '#0F151A',
    subtitleColor: '#0F151A',
    paragraphColor: '#323E47',
    shapeColor: '#D5E1ED',
    accentColor: '#D5E1ED',
    rectangleColor: '#D5E1ED',
    circleColor: '#D5E1ED',
    lineColor: '#92A6B2',
  },
  bigImage: {
    backgroundColor: '#FFFFFF',
    titleColor: '#0F151A',
    subtitleColor: '#0F151A',
    paragraphColor: '#323E47',
    shapeColor: '#D5E1ED',
    accentColor: '#D5E1ED',
    rectangleColor: '#D5E1ED',
    circleColor: '#D5E1ED',
    lineColor: '#92A6B2',
  },
  conclusion: {
    backgroundColor: '#FFFFFF',
    titleColor: '#0F151A',
    subtitleColor: '#0F151A',
    paragraphColor: '#323E47',
    shapeColor: '#D5E1ED',
    accentColor: '#D5E1ED',
    rectangleColor: '#D5E1ED',
    circleColor: '#D5E1ED',
    lineColor: '#92A6B2',
  },
  table: {
    backgroundColor: '#FFFFFF',
    headerBackgroundColor: '#FFF9E7',
    headerTextColor: '#8D6E0D',
    textColor: '#0F151A',
    cellBackgroundColor: '#FFFFFF',
  },
  cards: {
    backgroundColor: '#FFFFFF',
    titleColor: '#0F151A',
    subtitleColor: '#0F151A',
    paragraphColor: '#323E47',
    shapeColor: '#D5E1ED',
    accentColor: '#D5E1ED',
    rectangleColor: '#D5E1ED',
    circleColor: '#D5E1ED',
    lineColor: '#92A6B2',
  },
};

export const playfulLearning: SlideTheme = {
  name: 'Playful Learning',
  cover: {
    backgroundColor: '#EDF2FF',
    backgroundImage: '/images/slide-themes/bg-playful-learning.svg',
    titleColor: '#323E47',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  summary: {
    backgroundColor: '#EDF2FF',
    backgroundImage: '/images/slide-themes/bg-playful-learning.svg',
    titleColor: '#323E47',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  developmentBullet: {
    backgroundColor: '#EDF2FF',
    backgroundImage: '/images/slide-themes/bg-playful-learning.svg',
    titleColor: '#323E47',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  developmentText: {
    backgroundColor: '#EDF2FF',
    backgroundImage: '/images/slide-themes/bg-playful-learning.svg',
    titleColor: '#323E47',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  twoColumns: {
    backgroundColor: '#EDF2FF',
    backgroundImage: '/images/slide-themes/bg-playful-learning.svg',
    titleColor: '#323E47',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  exercise: {
    backgroundColor: '#EDF2FF',
    backgroundImage: '/images/slide-themes/bg-playful-learning.svg',
    titleColor: '#323E47',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  mainImage: {
    backgroundColor: '#EDF2FF',
    backgroundImage: '/images/slide-themes/bg-playful-learning.svg',
    titleColor: '#323E47',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  bigImage: {
    backgroundColor: '#EDF2FF',
    titleColor: '#323E47',
    backgroundImage: '/images/slide-themes/bg-playful-learning.svg',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  conclusion: {
    backgroundColor: '#EDF2FF',
    backgroundImage: '/images/slide-themes/bg-playful-learning.svg',
    titleColor: '#323E47',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  table: {
    ...tableColors,
    headerTextColor: '#323E47',
    headerBackgroundColor: '#eff5fb',
  },
  cards: {
    backgroundColor: '#EDF2FF',
    backgroundImage: '/images/slide-themes/bg-playful-learning.svg',
    titleColor: '#323E47',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
};

export const doodles: SlideTheme = {
  name: 'Doodles',
  cover: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-doodles.svg',
    titleColor: '#5880F1',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#5880F1',
  },
  summary: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-doodles.svg',
    titleColor: '#5880F1',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#5880F1',
  },
  developmentBullet: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-doodles.svg',
    titleColor: '#5880F1',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#5880F1',
  },
  developmentText: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-doodles.svg',
    titleColor: '#5880F1',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#5880F1',
  },
  twoColumns: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-doodles.svg',
    titleColor: '#5880F1',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#5880F1',
  },
  exercise: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-doodles.svg',
    titleColor: '#5880F1',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#5880F1',
  },
  mainImage: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-doodles.svg',
    titleColor: '#5880F1',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#5880F1',
  },
  bigImage: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-doodles.svg',
    titleColor: '#5880F1',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#5880F1',
  },
  conclusion: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-doodles.svg',
    titleColor: '#5880F1',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#5880F1',
  },
  table: {
    ...tableColors,
    headerTextColor: '#323E47',
    headerBackgroundColor: '#eff5fb',
  },
  cards: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-doodles.svg',
    titleColor: '#5880F1',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#5880F1',
  },
};

export const autumnLeaves: SlideTheme = {
  name: 'Autumn Leaves',
  cover: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-autumn-leaves.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#C6E9E7',
    accentColor: '#C6E9E7',
    rectangleColor: '#C6E9E7',
    circleColor: '#C6E9E7',
    lineColor: '#0F151A',
  },
  summary: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-autumn-leaves.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#C6E9E7',
    accentColor: '#C6E9E7',
    rectangleColor: '#C6E9E7',
    circleColor: '#C6E9E7',
    lineColor: '#0F151A',
  },
  developmentBullet: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-autumn-leaves.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#C6E9E7',
    accentColor: '#C6E9E7',
    rectangleColor: '#C6E9E7',
    circleColor: '#C6E9E7',
    lineColor: '#0F151A',
  },
  developmentText: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-autumn-leaves.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#C6E9E7',
    accentColor: '#C6E9E7',
    rectangleColor: '#C6E9E7',
    circleColor: '#C6E9E7',
    lineColor: '#0F151A',
  },
  twoColumns: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-autumn-leaves.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#C6E9E7',
    accentColor: '#C6E9E7',
    rectangleColor: '#C6E9E7',
    circleColor: '#C6E9E7',
    lineColor: '#0F151A',
  },
  exercise: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-autumn-leaves.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#C6E9E7',
    accentColor: '#C6E9E7',
    rectangleColor: '#C6E9E7',
    circleColor: '#C6E9E7',
    lineColor: '#0F151A',
  },
  mainImage: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-autumn-leaves.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#C6E9E7',
    accentColor: '#C6E9E7',
    rectangleColor: '#C6E9E7',
    circleColor: '#C6E9E7',
    lineColor: '#0F151A',
  },
  bigImage: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-autumn-leaves.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#C6E9E7',
    accentColor: '#C6E9E7',
    rectangleColor: '#C6E9E7',
    circleColor: '#C6E9E7',
    lineColor: '#0F151A',
  },
  conclusion: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-autumn-leaves.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#C6E9E7',
    accentColor: '#C6E9E7',
    rectangleColor: '#C6E9E7',
    circleColor: '#C6E9E7',
    lineColor: '#0F151A',
  },
  table: {
    ...tableColors,
    headerTextColor: '#323E47',
    headerBackgroundColor: '#eff5fb',
  },
  cards: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-autumn-leaves.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#C6E9E7',
    accentColor: '#C6E9E7',
    rectangleColor: '#C6E9E7',
    circleColor: '#C6E9E7',
    lineColor: '#0F151A',
  },
};

export const sciencePark: SlideTheme = {
  name: 'Science Park',
  cover: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-science-park.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  summary: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-science-park.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  developmentBullet: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-science-park.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  developmentText: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-science-park.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  twoColumns: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-science-park.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  exercise: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-science-park.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  mainImage: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-science-park.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  bigImage: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-science-park.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  conclusion: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-science-park.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  table: {
    ...tableColors,
    headerTextColor: '#323E47',
    headerBackgroundColor: '#eff5fb',
  },
  cards: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-science-park.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
};

export const notebookLines: SlideTheme = {
  name: 'Notebook Lines',
  cover: {
    backgroundColor: '#EDF2FF',
    backgroundImage: '/images/slide-themes/bg-notebook-lines.svg',
    titleColor: '#3055BF',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D5E1ED',
    accentColor: '#D5E1ED',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  summary: {
    backgroundColor: '#EDF2FF',
    backgroundImage: '/images/slide-themes/bg-notebook-lines.svg',
    titleColor: '#3055BF',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D5E1ED',
    accentColor: '#D5E1ED',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  developmentBullet: {
    backgroundColor: '#EDF2FF',
    backgroundImage: '/images/slide-themes/bg-notebook-lines.svg',
    titleColor: '#3055BF',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D5E1ED',
    accentColor: '#D5E1ED',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  developmentText: {
    backgroundColor: '#EDF2FF',
    backgroundImage: '/images/slide-themes/bg-notebook-lines.svg',
    titleColor: '#3055BF',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D5E1ED',
    accentColor: '#D5E1ED',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  twoColumns: {
    backgroundColor: '#EDF2FF',
    backgroundImage: '/images/slide-themes/bg-notebook-lines.svg',
    titleColor: '#3055BF',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D5E1ED',
    accentColor: '#D5E1ED',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  exercise: {
    backgroundColor: '#EDF2FF',
    backgroundImage: '/images/slide-themes/bg-notebook-lines.svg',
    titleColor: '#3055BF',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D5E1ED',
    accentColor: '#D5E1ED',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  mainImage: {
    backgroundColor: '#EDF2FF',
    backgroundImage: '/images/slide-themes/bg-notebook-lines.svg',
    titleColor: '#3055BF',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D5E1ED',
    accentColor: '#D5E1ED',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  bigImage: {
    backgroundColor: '#EDF2FF',
    backgroundImage: '/images/slide-themes/bg-notebook-lines.svg',
    titleColor: '#3055BF',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D5E1ED',
    accentColor: '#D5E1ED',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  conclusion: {
    backgroundColor: '#EDF2FF',
    backgroundImage: '/images/slide-themes/bg-notebook-lines.svg',
    titleColor: '#3055BF',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D5E1ED',
    accentColor: '#D5E1ED',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  table: {
    ...tableColors,
    headerTextColor: '#323E47',
    headerBackgroundColor: '#eff5fb',
  },
  cards: {
    backgroundColor: '#EDF2FF',
    backgroundImage: '/images/slide-themes/bg-notebook-lines.svg',
    titleColor: '#3055BF',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D5E1ED',
    accentColor: '#D5E1ED',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
};

export const creativeGrid: SlideTheme = {
  name: 'Creative Grid',
  cover: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-creative-grid.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  summary: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-creative-grid.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  developmentBullet: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-creative-grid.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  developmentText: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-creative-grid.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  twoColumns: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-creative-grid.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  exercise: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-creative-grid.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  mainImage: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-creative-grid.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  bigImage: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-creative-grid.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  conclusion: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-creative-grid.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  table: {
    ...tableColors,
    headerTextColor: '#323E47',
    headerBackgroundColor: '#eff5fb',
  },
  cards: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-creative-grid.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#D2DEFF',
    accentColor: '#D2DEFF',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
};

export const softBloom: SlideTheme = {
  name: 'Soft Bloom',
  cover: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-soft-bloom.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#C6E9E7',
    accentColor: '#C6E9E7',
    rectangleColor: '#C6E9E7',
    circleColor: '#C6E9E7',
    lineColor: '#0F151A',
  },
  summary: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-soft-bloom.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#C6E9E7',
    accentColor: '#C6E9E7',
    rectangleColor: '#C6E9E7',
    circleColor: '#C6E9E7',
    lineColor: '#0F151A',
  },
  developmentBullet: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-soft-bloom.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#C6E9E7',
    accentColor: '#C6E9E7',
    rectangleColor: '#C6E9E7',
    circleColor: '#C6E9E7',
    lineColor: '#0F151A',
  },
  developmentText: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-soft-bloom.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#C6E9E7',
    accentColor: '#C6E9E7',
    rectangleColor: '#C6E9E7',
    circleColor: '#C6E9E7',
    lineColor: '#0F151A',
  },
  twoColumns: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-soft-bloom.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#C6E9E7',
    accentColor: '#C6E9E7',
    rectangleColor: '#C6E9E7',
    circleColor: '#C6E9E7',
    lineColor: '#0F151A',
  },
  exercise: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-soft-bloom.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#C6E9E7',
    accentColor: '#C6E9E7',
    rectangleColor: '#C6E9E7',
    circleColor: '#C6E9E7',
    lineColor: '#0F151A',
  },
  mainImage: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-soft-bloom.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#C6E9E7',
    accentColor: '#C6E9E7',
    rectangleColor: '#C6E9E7',
    circleColor: '#C6E9E7',
    lineColor: '#0F151A',
  },
  bigImage: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-soft-bloom.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#C6E9E7',
    accentColor: '#C6E9E7',
    rectangleColor: '#C6E9E7',
    circleColor: '#C6E9E7',
    lineColor: '#0F151A',
  },
  conclusion: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-soft-bloom.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#C6E9E7',
    accentColor: '#C6E9E7',
    rectangleColor: '#C6E9E7',
    circleColor: '#C6E9E7',
    lineColor: '#0F151A',
  },
  table: {
    ...tableColors,
    headerTextColor: '#323E47',
    headerBackgroundColor: '#eff5fb',
  },
  cards: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-soft-bloom.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#C6E9E7',
    accentColor: '#C6E9E7',
    rectangleColor: '#C6E9E7',
    circleColor: '#C6E9E7',
    lineColor: '#0F151A',
  },
};

export const calmGlow: SlideTheme = {
  name: 'Calm Glow',
  cover: {
    backgroundColor: '#80A1FF',
    backgroundImage: '/images/slide-themes/bg-calm-glow.svg',
    titleColor: '#0F151A',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#EFF5FB',
    accentColor: '#EFF5FB',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  summary: {
    backgroundColor: '#80A1FF',
    backgroundImage: '/images/slide-themes/bg-calm-glow.svg',
    titleColor: '#0F151A',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#EFF5FB',
    accentColor: '#EFF5FB',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  developmentBullet: {
    backgroundColor: '#80A1FF',
    backgroundImage: '/images/slide-themes/bg-calm-glow.svg',
    titleColor: '#0F151A',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#EFF5FB',
    accentColor: '#EFF5FB',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  developmentText: {
    backgroundColor: '#80A1FF',
    backgroundImage: '/images/slide-themes/bg-calm-glow.svg',
    titleColor: '#0F151A',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#EFF5FB',
    accentColor: '#EFF5FB',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  twoColumns: {
    backgroundColor: '#80A1FF',
    backgroundImage: '/images/slide-themes/bg-calm-glow.svg',
    titleColor: '#0F151A',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#EFF5FB',
    accentColor: '#EFF5FB',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  exercise: {
    backgroundColor: '#80A1FF',
    backgroundImage: '/images/slide-themes/bg-calm-glow.svg',
    titleColor: '#0F151A',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#EFF5FB',
    accentColor: '#EFF5FB',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  mainImage: {
    backgroundColor: '#80A1FF',
    backgroundImage: '/images/slide-themes/bg-calm-glow.svg',
    titleColor: '#0F151A',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#EFF5FB',
    accentColor: '#EFF5FB',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  bigImage: {
    backgroundColor: '#80A1FF',
    backgroundImage: '/images/slide-themes/bg-calm-glow.svg',
    titleColor: '#0F151A',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#EFF5FB',
    accentColor: '#EFF5FB',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  conclusion: {
    backgroundColor: '#80A1FF',
    backgroundImage: '/images/slide-themes/bg-calm-glow.svg',
    titleColor: '#0F151A',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#EFF5FB',
    accentColor: '#EFF5FB',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  table: {
    ...tableColors,
    headerTextColor: '#323E47',
    headerBackgroundColor: '#eff5fb',
  },
  cards: {
    backgroundColor: '#80A1FF',
    backgroundImage: '/images/slide-themes/bg-calm-glow.svg',
    titleColor: '#0F151A',
    subtitleColor: '#0F151A',
    paragraphColor: '#0F151A',
    shapeColor: '#EFF5FB',
    accentColor: '#EFF5FB',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
};

export const browsingForKnowledge: SlideTheme = {
  name: 'Browsing for Knowledge',
  cover: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-browsing-for-knowledge.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#A3D9D5',
    accentColor: '#A3D9D5',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  summary: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-browsing-for-knowledge.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#A3D9D5',
    accentColor: '#A3D9D5',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  developmentBullet: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-browsing-for-knowledge.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#A3D9D5',
    accentColor: '#A3D9D5',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  developmentText: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-browsing-for-knowledge.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#A3D9D5',
    accentColor: '#A3D9D5',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  twoColumns: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-browsing-for-knowledge.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#A3D9D5',
    accentColor: '#A3D9D5',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  exercise: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-browsing-for-knowledge.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#A3D9D5',
    accentColor: '#A3D9D5',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  mainImage: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-browsing-for-knowledge.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#A3D9D5',
    accentColor: '#A3D9D5',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  bigImage: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-browsing-for-knowledge.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#A3D9D5',
    accentColor: '#A3D9D5',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  conclusion: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-browsing-for-knowledge.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#A3D9D5',
    accentColor: '#A3D9D5',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
  table: {
    ...tableColors,
    headerTextColor: '#323E47',
    headerBackgroundColor: '#eff5fb',
  },
  cards: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-browsing-for-knowledge.svg',
    titleColor: '#0F151A',
    subtitleColor: '#323E47',
    paragraphColor: '#323E47',
    shapeColor: '#A3D9D5',
    accentColor: '#A3D9D5',
    rectangleColor: '#D2DEFF',
    circleColor: '#D2DEFF',
    lineColor: '#323E47',
  },
};

export const darkMode: SlideTheme = {
  name: 'Dark Mode',
  cover: {
    backgroundColor: '#0F151A',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#80A1FF',
    accentColor: '#80A1FF',
    rectangleColor: '#323E47',
    circleColor: '#323E47',
    lineColor: '#80A1FF',
  },
  summary: {
    backgroundColor: '#0F151A',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#80A1FF',
    accentColor: '#80A1FF',
    rectangleColor: '#323E47',
    circleColor: '#323E47',
    lineColor: '#80A1FF',
  },
  developmentBullet: {
    backgroundColor: '#0F151A',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#80A1FF',
    accentColor: '#80A1FF',
    rectangleColor: '#323E47',
    circleColor: '#323E47',
    lineColor: '#80A1FF',
  },
  developmentText: {
    backgroundColor: '#0F151A',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#80A1FF',
    accentColor: '#80A1FF',
    rectangleColor: '#323E47',
    circleColor: '#323E47',
    lineColor: '#80A1FF',
  },
  twoColumns: {
    backgroundColor: '#0F151A',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#80A1FF',
    accentColor: '#80A1FF',
    rectangleColor: '#323E47',
    circleColor: '#323E47',
    lineColor: '#80A1FF',
  },
  exercise: {
    backgroundColor: '#0F151A',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#80A1FF',
    accentColor: '#80A1FF',
    rectangleColor: '#323E47',
    circleColor: '#323E47',
    lineColor: '#80A1FF',
  },
  mainImage: {
    backgroundColor: '#0F151A',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#80A1FF',
    accentColor: '#80A1FF',
    rectangleColor: '#323E47',
    circleColor: '#323E47',
    lineColor: '#80A1FF',
  },
  bigImage: {
    backgroundColor: '#0F151A',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#80A1FF',
    accentColor: '#80A1FF',
    rectangleColor: '#323E47',
    circleColor: '#323E47',
    lineColor: '#80A1FF',
  },
  conclusion: {
    backgroundColor: '#0F151A',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#80A1FF',
    accentColor: '#80A1FF',
    rectangleColor: '#323E47',
    circleColor: '#323E47',
    lineColor: '#80A1FF',
  },
  table: {
    backgroundColor: '#0F151A',
    headerBackgroundColor: '#17232B',
    headerTextColor: '#FFFFFF',
    textColor: '#FFFFFF',
    cellBackgroundColor: '#323E47',
  },
  cards: {
    backgroundColor: '#0F151A',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#80A1FF',
    accentColor: '#80A1FF',
    rectangleColor: '#323E47',
    circleColor: '#323E47',
    lineColor: '#80A1FF',
  },
};

export const midnightLearning: SlideTheme = {
  name: 'Midnight Learning',
  cover: {
    backgroundColor: '#1A2375',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#80A1FF',
    accentColor: '#80A1FF',
    rectangleColor: '#000746',
    circleColor: '#000746',
    lineColor: '#80A1FF',
  },
  summary: {
    backgroundColor: '#1A2375',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#80A1FF',
    accentColor: '#80A1FF',
    rectangleColor: '#000746',
    circleColor: '#000746',
    lineColor: '#80A1FF',
  },
  developmentBullet: {
    backgroundColor: '#1A2375',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#80A1FF',
    accentColor: '#80A1FF',
    rectangleColor: '#000746',
    circleColor: '#000746',
    lineColor: '#80A1FF',
  },
  developmentText: {
    backgroundColor: '#1A2375',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#80A1FF',
    accentColor: '#80A1FF',
    rectangleColor: '#000746',
    circleColor: '#000746',
    lineColor: '#80A1FF',
  },
  twoColumns: {
    backgroundColor: '#1A2375',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#80A1FF',
    accentColor: '#80A1FF',
    rectangleColor: '#000746',
    circleColor: '#000746',
    lineColor: '#80A1FF',
  },
  exercise: {
    backgroundColor: '#1A2375',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#80A1FF',
    accentColor: '#80A1FF',
    rectangleColor: '#000746',
    circleColor: '#000746',
    lineColor: '#80A1FF',
  },
  mainImage: {
    backgroundColor: '#1A2375',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#80A1FF',
    accentColor: '#80A1FF',
    rectangleColor: '#000746',
    circleColor: '#000746',
    lineColor: '#80A1FF',
  },
  bigImage: {
    backgroundColor: '#1A2375',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#80A1FF',
    accentColor: '#80A1FF',
    rectangleColor: '#000746',
    circleColor: '#000746',
    lineColor: '#80A1FF',
  },
  conclusion: {
    backgroundColor: '#1A2375',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#80A1FF',
    accentColor: '#80A1FF',
    rectangleColor: '#000746',
    circleColor: '#000746',
    lineColor: '#80A1FF',
  },
  table: {
    backgroundColor: '#1A2375',
    headerBackgroundColor: '#00063B',
    headerTextColor: '#FFFFFF',
    textColor: '#FFFFFF',
    cellBackgroundColor: '#09136C',
  },
  cards: {
    backgroundColor: '#1A2375',
    titleColor: '#FFFFFF',
    subtitleColor: '#FFFFFF',
    paragraphColor: '#FFFFFF',
    shapeColor: '#80A1FF',
    accentColor: '#80A1FF',
    rectangleColor: '#000746',
    circleColor: '#000746',
    lineColor: '#80A1FF',
  },
};

export const brightOrganic: SlideTheme = {
  name: 'Bright Organic',
  isPremium: true,
  cover: {
    backgroundColor: '#CBE6FF',
    backgroundImage: '/images/slide-themes/premium-one/cover-p-1.svg',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#6F9DF9',
    accentColor: '#6F9DF9',
    rectangleColor: '#6F9DF9',
    circleColor: '#6F9DF9',
    lineColor: '#6F9DF9',
    decorativeImage: undefined,
  },
  summary: {
    backgroundColor: '#CBE6FF',
    backgroundImage: '',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#6F9DF9',
    accentColor: '#6F9DF9',
    rectangleColor: '#6F9DF9',
    circleColor: '#6F9DF9',
    lineColor: '#6F9DF9',
    decorativeImage: undefined,
  },
  developmentBullet: {
    backgroundColor: '#CBE6FF',
    backgroundImage:
      '/images/slide-themes/premium-one/development-text-p-1.svg',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#6F9DF9',
    accentColor: '#6F9DF9',
    rectangleColor: '#6F9DF9',
    circleColor: '#6F9DF9',
    lineColor: '#6F9DF9',
    decorativeImage: undefined,
  },
  developmentText: {
    backgroundColor: '#CBE6FF',
    backgroundImage:
      '/images/slide-themes/premium-one/development-text-p-1.svg',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#6F9DF9',
    accentColor: '#6F9DF9',
    rectangleColor: '#6F9DF9',
    circleColor: '#6F9DF9',
    lineColor: '#6F9DF9',
    decorativeImage: undefined,
  },
  twoColumns: {
    backgroundColor: '#CBE6FF',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#6F9DF9',
    accentColor: '#6F9DF9',
    rectangleColor: '#6F9DF9',
    circleColor: '#6F9DF9',
    lineColor: '#6F9DF9',
    decorativeImage: [
      {
        src: '/images/slide-themes/premium-one/down-arrow.svg',
        x: 1400,
        y: 45.78,
        width: 60,
        height: 70,
      },
      {
        src: '/images/slide-themes/premium-one/down-arrow.svg',
        x: 520,
        y: 45.78,
        width: 60,
        height: 70,
      },
    ],
  },
  exercise: {
    backgroundColor: '#CBE6FF',
    backgroundImage:
      '/images/slide-themes/premium-one/development-text-p-1.svg',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#6F9DF9',
    accentColor: '#6F9DF9',
    rectangleColor: '#6F9DF9',
    circleColor: '#6F9DF9',
    lineColor: '#6F9DF9',
    decorativeImage: undefined,
  },
  mainImage: {
    backgroundColor: '#CBE6FF',
    backgroundImage:
      '/images/slide-themes/premium-one/development-bullet-p-1.svg',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#6F9DF9',
    accentColor: '#6F9DF9',
    rectangleColor: '#6F9DF9',
    circleColor: '#6F9DF9',
    lineColor: '#6F9DF9',
    decorativeImage: undefined,
  },
  bigImage: {
    backgroundColor: '#CBE6FF',
    backgroundImage: '/images/slide-themes/premium-one/card-p-1.svg',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#6F9DF9',
    accentColor: '#6F9DF9',
    rectangleColor: '#6F9DF9',
    circleColor: '#6F9DF9',
    lineColor: '#6F9DF9',
    decorativeImage: undefined,
  },
  conclusion: {
    backgroundColor: '#CBE6FF',
    backgroundImage: '/images/slide-themes/premium-one/card-p-1.svg',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#6F9DF9',
    accentColor: '#6F9DF9',
    rectangleColor: '#6F9DF9',
    circleColor: '#6F9DF9',
    lineColor: '#6F9DF9',
    decorativeImage: undefined,
  },
  table: {
    ...tableColors,
    headerTextColor: '#161C2E',
    headerBackgroundColor: '#ffffff',
  },
  cards: {
    backgroundColor: '#CBE6FF',
    backgroundImage: '/images/slide-themes/premium-one/card-p-1.svg',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#6F9DF9',
    accentColor: '#6F9DF9',
    rectangleColor: '#6F9DF9',
    circleColor: '#6F9DF9',
    lineColor: '#6F9DF9',
    decorativeImage: undefined,
  },
};

export const riseAndLearn: SlideTheme = {
  name: 'Rise and Learn',
  isPremium: true,
  cover: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/premium-two/cover-p-2.svg',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#CAE7FF',
    accentColor: '#CAE7FF',
    rectangleColor: '#CAE7FF',
    circleColor: '#CAE7FF',
    lineColor: '#CAE7FF',
    decorativeImage: [
      {
        src: '/images/slide-themes/premium-two/lara-happy.svg',
        x: 1112,
        y: 489,
        width: 730,
        height: 730,
      },
    ],
  },
  summary: {
    backgroundColor: '#E3F3FF',
    backgroundImage: '/images/slide-themes/premium-two/summary-p-2.svg',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#CAE7FF',
    accentColor: '#CAE7FF',
    rectangleColor: '#CAE7FF',
    circleColor: '#CAE7FF',
    lineColor: '#CAE7FF',
    decorativeImage: undefined,
  },
  developmentBullet: {
    backgroundColor: '#F6FBFF',
    backgroundImage: '/images/slide-themes/premium-two/dev-bullet-p-2.svg',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#CAE7FF',
    accentColor: '#CAE7FF',
    rectangleColor: '#CAE7FF',
    circleColor: '#CAE7FF',
    lineColor: '#CAE7FF',
    decorativeImage: undefined,
  },
  developmentText: {
    backgroundColor: '#F6FBFF',
    backgroundImage: '/images/slide-themes/premium-two/dev-text-p-2.svg',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#CAE7FF',
    accentColor: '#CAE7FF',
    rectangleColor: '#CAE7FF',
    circleColor: '#CAE7FF',
    lineColor: '#CAE7FF',
    decorativeImage: undefined,
  },
  imageAndText: {
    backgroundColor: '#F6FBFF',
    backgroundImage: '/images/slide-themes/premium-two/image-text-p-2.svg',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#CAE7FF',
    accentColor: '#CAE7FF',
    rectangleColor: '#CAE7FF',
    circleColor: '#CAE7FF',
    lineColor: '#CAE7FF',
    decorativeImage: undefined,
  },
  textAndImage: {
    backgroundColor: '#F6FBFF',
    backgroundImage: '/images/slide-themes/premium-two/text-image-p-2.svg',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#CAE7FF',
    accentColor: '#CAE7FF',
    rectangleColor: '#CAE7FF',
    circleColor: '#CAE7FF',
    lineColor: '#CAE7FF',
  },
  twoColumns: {
    backgroundColor: '#F6FBFF',
    titleBackgroundImage: '/images/slide-themes/premium-two/title-bg.svg',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#CAE7FF',
    accentColor: '#CAE7FF',
    rectangleColor: '#CAE7FF',
    circleColor: '#CAE7FF',
    lineColor: '#CAE7FF',
  },
  exercise: {
    backgroundColor: '#E3F3FF',
    backgroundImage: '/images/slide-themes/premium-two/exercise-p-2.svg',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#CAE7FF',
    accentColor: '#CAE7FF',
    rectangleColor: '#CAE7FF',
    circleColor: '#CAE7FF',
    lineColor: '#CAE7FF',
    decorativeImage: undefined,
  },
  mainImage: {
    backgroundColor: '#E3F3FF',
    backgroundImage: '/images/slide-themes/premium-two/conclusion-p-2.svg',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#CAE7FF',
    accentColor: '#CAE7FF',
    rectangleColor: '#CAE7FF',
    circleColor: '#CAE7FF',
    lineColor: '#CAE7FF',
    decorativeImage: undefined,
  },
  bigImage: {
    backgroundColor: '#E3F3FF',
    backgroundImage: '/images/slide-themes/premium-two/conclusion-p-2.svg',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#CAE7FF',
    accentColor: '#CAE7FF',
    rectangleColor: '#CAE7FF',
    circleColor: '#CAE7FF',
    lineColor: '#CAE7FF',
    decorativeImage: undefined,
  },
  imageDown: {
    backgroundColor: '#E3F3FF',
    backgroundImage: '/images/slide-themes/premium-two/image-down-p-2.svg',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#E3F3FF',
    accentColor: '#E3F3FF',
    rectangleColor: '#E3F3FF',
    circleColor: '#E3F3FF',
    lineColor: '#E3F3FF',
  },
  conclusion: {
    backgroundColor: '#E3F3FF',
    backgroundImage: '/images/slide-themes/premium-two/summary-p-2.svg',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#CAE7FF',
    accentColor: '#CAE7FF',
    rectangleColor: '#CAE7FF',
    circleColor: '#CAE7FF',
    lineColor: '#CAE7FF',
  },
  table: {
    ...tableColors,
    headerTextColor: '#161C2E',
    headerBackgroundColor: '#FFFFFF',
  },
  cards: {
    backgroundColor: '#E3F3FF',
    backgroundImage: '/images/slide-themes/premium-two/cards-p-2.svg',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#CAE7FF',
    accentColor: '#CAE7FF',
    rectangleColor: '#CAE7FF',
    circleColor: '#CAE7FF',
    lineColor: '#CAE7FF',
  },
};

export const teachyClean: SlideTheme = {
  name: 'Teachy Clean',
  isPremium: false,
  cover: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-teachy-clean.svg',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#8E9AAF',
    accentColor: '#161C2E',
    rectangleColor: '#D9DDE8',
    circleColor: '#D9DDE8',
    lineColor: '#8E9AAF',
  },
  summary: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-teachy-clean.svg',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#8E9AAF',
    accentColor: '#161C2E',
    rectangleColor: '#D9DDE8',
    circleColor: '#D9DDE8',
    lineColor: '#8E9AAF',
  },
  developmentBullet: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-teachy-clean.svg',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#8E9AAF',
    accentColor: '#161C2E',
    rectangleColor: '#D9DDE8',
    circleColor: '#D9DDE8',
    lineColor: '#8E9AAF',
  },
  developmentText: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-teachy-clean.svg',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#8E9AAF',
    accentColor: '#161C2E',
    rectangleColor: '#D9DDE8',
    circleColor: '#D9DDE8',
    lineColor: '#8E9AAF',
  },
  imageAndText: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-teachy-clean.svg',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#8E9AAF',
    accentColor: '#161C2E',
    rectangleColor: '#D9DDE8',
    circleColor: '#D9DDE8',
    lineColor: '#8E9AAF',
  },
  textAndImage: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-teachy-clean.svg',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#8E9AAF',
    accentColor: '#161C2E',
    rectangleColor: '#D9DDE8',
    circleColor: '#D9DDE8',
    lineColor: '#8E9AAF',
  },
  twoColumns: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-teachy-clean.svg',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#8E9AAF',
    accentColor: '#161C2E',
    rectangleColor: '#D9DDE8',
    circleColor: '#D9DDE8',
    lineColor: '#8E9AAF',
  },
  exercise: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-teachy-clean.svg',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#8E9AAF',
    accentColor: '#161C2E',
    rectangleColor: '#D9DDE8',
    circleColor: '#D9DDE8',
    lineColor: '#8E9AAF',
  },
  mainImage: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-teachy-clean.svg',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#8E9AAF',
    accentColor: '#161C2E',
    rectangleColor: '#D9DDE8',
    circleColor: '#D9DDE8',
    lineColor: '#8E9AAF',
  },
  bigImage: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-teachy-clean.svg',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#8E9AAF',
    accentColor: '#161C2E',
    rectangleColor: '#D9DDE8',
    circleColor: '#D9DDE8',
    lineColor: '#8E9AAF',
  },
  imageDown: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-teachy-clean.svg',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#8E9AAF',
    accentColor: '#161C2E',
    rectangleColor: '#D9DDE8',
    circleColor: '#D9DDE8',
    lineColor: '#8E9AAF',
  },
  conclusion: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-teachy-clean.svg',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#8E9AAF',
    accentColor: '#161C2E',
    rectangleColor: '#D9DDE8',
    circleColor: '#D9DDE8',
    lineColor: '#8E9AAF',
  },
  table: {
    ...tableColors,
    headerTextColor: '#161C2E',
    headerBackgroundColor: '#E7ECFC',
  },
  cards: {
    backgroundColor: '#FFFFFF',
    backgroundImage: '/images/slide-themes/bg-teachy-clean.svg',
    titleColor: '#161C2E',
    subtitleColor: '#161C2E',
    paragraphColor: '#161C2E',
    shapeColor: '#8E9AAF',
    accentColor: '#161C2E',
    rectangleColor: '#D9DDE8',
    circleColor: '#D9DDE8',
    lineColor: '#8E9AAF',
  },
};

/**
 * Available themes collection
 */
export const slideThemes = {
  classicChalk,
  darkMode,
  midnightLearning,
  // lightFun,
  deepKnowledge,
  softSky,
  growingIdeas,
  gentleNature,
  // brightMinds,
  // sunnyClassroom,
  playfulLearning,
  // doodles,
  // autumnLeaves,
  sciencePark,
  notebookLines,
  creativeGrid,
  softBloom,
  // calmGlow,
  // browsingForKnowledge,
  riseAndLearn,
  brightOrganic,
  teachyClean,
};

/**
 * Default theme (white theme)
 */
export const defaultTheme = classicChalk;
