import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/contexts/auth-context";
import { ThemeProvider } from "@/components/theme-provider";

// Usando fontes do sistema como fallback já que não há conectividade com Google Fonts
// Você pode descomentar as importações abaixo quando tiver internet
// import { Geist, Geist_Mono, Outfit } from "next/font/google";

// const outfit = Outfit({
//   subsets: ['latin'],
//   variable: '--font-sans',
//   display: 'swap',
//   fallback: ['system-ui', 'arial'],
// });

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
//   display: 'swap',
//   fallback: ['system-ui', 'arial'],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
//   display: 'swap',
//   fallback: ['monospace'],
// });

export const metadata: Metadata = {
  title: "Mais Docente",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ fontFamily: 'system-ui, -apple-system, sans-serif' }} suppressHydrationWarning>
      <body className="antialiased" suppressHydrationWarning>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            {children}
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
